// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2iMTRZeqH_Jm0xEzEKBsqo3UvxuSuys0',
    appId: '1:281060357755:web:9e209f9eb65d3e62f4d4de',
    messagingSenderId: '281060357755',
    projectId: 'civar-dev',
    authDomain: 'civar-dev.firebaseapp.com',
    storageBucket: 'civar-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb1sPlOuPawaVHyljY_GbSI94ws-thfZM',
    appId: '1:281060357755:android:e5b4584b3cb9c664f4d4de',
    messagingSenderId: '281060357755',
    projectId: 'civar-dev',
    storageBucket: 'civar-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYJQsZDIEu4b2plc5uARjmFkAK-AJhBgI',
    appId: '1:281060357755:ios:ba8de220cf74f1b0f4d4de',
    messagingSenderId: '281060357755',
    projectId: 'civar-dev',
    storageBucket: 'civar-dev.firebasestorage.app',
    iosClientId: '281060357755-8uii37qhmtanok1muphsd3e6nm7n76gl.apps.googleusercontent.com',
    iosBundleId: 'com.civar.civar',
  );
}
